In [18]:
import numpy as np
my_np_list = np.array([[0,1,2],[3,4,6],[7,8,9]], dtype = 'float32' )
print(type(my_np_list)) # get a type of array
print(my_np_list + 2) # add number to all elemnts of the list
print(my_np_list.astype('int'))
my_list = my_np_list.tolist() # convert numpy array to list
print(my_list)

<class 'numpy.ndarray'>
[[ 2.  3.  4.]
 [ 5.  6.  8.]
 [ 9. 10. 11.]]
[[0 1 2]
 [3 4 6]
 [7 8 9]]
[[0.0, 1.0, 2.0], [3.0, 4.0, 6.0], [7.0, 8.0, 9.0]]


In [19]:
zeros_list = np.zeros((5,5))
print(zeros_list)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [20]:
ones_list = np.ones((5,5))
print(ones_list)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [21]:
identity_list = np.identity(5)
print(identity_list)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [35]:
x = np.arange(10)
print(x, 'Size :' , x.shape)
y = np.ones(10)
print(y, 'Size :' , y.shape)
z = x + y
result = z.reshape(10,1)
print(result + x)

[0 1 2 3 4 5 6 7 8 9] Size : (10,)
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] Size : (10,)
[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
 [ 3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]
 [ 4.  5.  6.  7.  8.  9. 10. 11. 12. 13.]
 [ 5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]
 [ 6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]
 [ 7.  8.  9. 10. 11. 12. 13. 14. 15. 16.]
 [ 8.  9. 10. 11. 12. 13. 14. 15. 16. 17.]
 [ 9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]]
